export const SAVE_ARTISTS = "SAVE_ARTISTS";
export const CLEAR_ARTISTS = "CLEAR_ARTISTS";
export const UPDATE_ARTISTS = "UPDATE_ARTISTS";

export const SAVE_ARTIST_DETAIL = "SAVE_ARTIST_DETAIL";
export const CLEAR_ARTIST_DETAIL = "CLEAR_ARTIST_DETAIL";
export const UPDATE_ARTIST_DETAIL = "UPDATE_ARTIST_DETAIL";

export const SAVE_TRENDING_ARTISTS = "SAVE_TRENDING_ARTISTS";
export const CLEAR_TRENDING_ARTIST = "CLEAR_TRENDING_ARTIST";
export const UPDATE_TRENDING_ARTIST = "UPDATE_TRENDING_ARTIST";

export const SAVE_ARTIST_RELATED = "SAVE_ARTIST_RELATED";
