export const SAVE_TRACKS = "SAVE_TRACKS";
export const CLEAR_TRACKS = "CLEAR_TRACKS";
export const UPDATE_TRACKS = "UPDATE_TRACKS";

export const SAVE_TRACK_DETAIL = "SAVE_TRACK_DETAIL";
export const CLEAR_TRACK_DETAIL = "CLEAR_TRACK_DETAIL";
export const UPDATE_TRACK_DETAIL = "UPDATE_TRACK_DETAIL";
